/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicLeadNotifyRouteImport } from './routes/api/public/lead-notify'
import { Route as ApiPublicAttomHealthRouteImport } from './routes/api/public/attom-health'
import { Route as ApiEnginesTtsRouteImport } from './routes/api/engines/tts'
import { Route as AuthenticatedBillingReturnRouteImport } from './routes/_authenticated/billing.return'
import { Route as AuthenticatedAppWatchlistRouteImport } from './routes/_authenticated/app.watchlist'
import { Route as AuthenticatedAppVisionRouteImport } from './routes/_authenticated/app.vision'
import { Route as AuthenticatedAppVideosRouteImport } from './routes/_authenticated/app.videos'
import { Route as AuthenticatedAppTitleSearchRouteImport } from './routes/_authenticated/app.title-search'
import { Route as AuthenticatedAppSocialRouteImport } from './routes/_authenticated/app.social'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppScoringRouteImport } from './routes/_authenticated/app.scoring'
import { Route as AuthenticatedAppPropertiesRouteImport } from './routes/_authenticated/app.properties'
import { Route as AuthenticatedAppOwnersRouteImport } from './routes/_authenticated/app.owners'
import { Route as AuthenticatedAppOutreachRouteImport } from './routes/_authenticated/app.outreach'
import { Route as AuthenticatedAppOptOutsRouteImport } from './routes/_authenticated/app.opt-outs'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppLeadListsRouteImport } from './routes/_authenticated/app.lead-lists'
import { Route as AuthenticatedAppForeclosureAgentRouteImport } from './routes/_authenticated/app.foreclosure-agent'
import { Route as AuthenticatedAppContractsRouteImport } from './routes/_authenticated/app.contracts'
import { Route as AuthenticatedAppContactsRouteImport } from './routes/_authenticated/app.contacts'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as AuthenticatedAppAuctionsRouteImport } from './routes/_authenticated/app.auctions'
import { Route as AuthenticatedAppAgentRouteImport } from './routes/_authenticated/app.agent'
import { Route as AuthenticatedAppPropertiesIndexRouteImport } from './routes/_authenticated/app.properties.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicHooksTwilioVoiceRouteImport } from './routes/api/public/hooks/twilio-voice'
import { Route as ApiPublicHooksTwilioSmsRouteImport } from './routes/api/public/hooks/twilio-sms'
import { Route as ApiPublicHooksSyncDistressedOneRouteImport } from './routes/api/public/hooks/sync-distressed-one'
import { Route as ApiPublicHooksSyncDistressedRouteImport } from './routes/api/public/hooks/sync-distressed'
import { Route as ApiPublicHooksSignwellRouteImport } from './routes/api/public/hooks/signwell'
import { Route as ApiPublicHooksOutreachReplyRouteImport } from './routes/api/public/hooks/outreach-reply'
import { Route as ApiPublicHooksNotifySmsRouteImport } from './routes/api/public/hooks/notify-sms'
import { Route as ApiPublicHooksComplianceDigestRouteImport } from './routes/api/public/hooks/compliance-digest'
import { Route as ApiPublicHooksCloseAuctionsRouteImport } from './routes/api/public/hooks/close-auctions'
import { Route as AgentsSlugPPostSlugRouteImport } from './routes/agents.$slug.p.$postSlug'
import { Route as AuthenticatedAppVisionLibraryRouteImport } from './routes/_authenticated/app.vision.library'
import { Route as AuthenticatedAppTitleSearchHistoryRouteImport } from './routes/_authenticated/app.title-search.history'
import { Route as AuthenticatedAppSocialComposeRouteImport } from './routes/_authenticated/app.social.compose'
import { Route as AuthenticatedAppSocialBusinessPortfolioRouteImport } from './routes/_authenticated/app.social.business-portfolio'
import { Route as AuthenticatedAppSettingsPublicProfileRouteImport } from './routes/_authenticated/app.settings.public-profile'
import { Route as AuthenticatedAppSettingsIntegrationsRouteImport } from './routes/_authenticated/app.settings.integrations'
import { Route as AuthenticatedAppPropertiesSearchRouteImport } from './routes/_authenticated/app.properties.search'
import { Route as AuthenticatedAppPropertiesLookupHistoryRouteImport } from './routes/_authenticated/app.properties.lookup-history'
import { Route as AuthenticatedAppPropertiesLookupRouteImport } from './routes/_authenticated/app.properties.lookup'
import { Route as AuthenticatedAppPropertiesPropertyIdRouteImport } from './routes/_authenticated/app.properties.$propertyId'
import { Route as AuthenticatedAppLeadsLeadIdRouteImport } from './routes/_authenticated/app.leads.$leadId'
import { Route as AuthenticatedAppContractsContractIdRouteImport } from './routes/_authenticated/app.contracts.$contractId'
import { Route as AuthenticatedAppAuctionsAuctionIdRouteImport } from './routes/_authenticated/app.auctions.$auctionId'
import { Route as AuthenticatedAppAgentThreadIdRouteImport } from './routes/_authenticated/app.agent.$threadId'
import { Route as AuthenticatedAppAdminContractsRouteImport } from './routes/_authenticated/app.admin.contracts'
import { Route as ApiPublicOauthYoutubeStartRouteImport } from './routes/api/public/oauth/youtube.start'
import { Route as ApiPublicOauthXStartRouteImport } from './routes/api/public/oauth/x.start'
import { Route as ApiPublicOauthMetaStartRouteImport } from './routes/api/public/oauth/meta.start'
import { Route as ApiPublicOauthMetaCallbackRouteImport } from './routes/api/public/oauth/meta.callback'
import { Route as AuthenticatedAppAdminContractsContractIdRouteImport } from './routes/_authenticated/app.admin.contracts.$contractId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadNotifyRoute = ApiPublicLeadNotifyRouteImport.update({
  id: '/api/public/lead-notify',
  path: '/api/public/lead-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAttomHealthRoute = ApiPublicAttomHealthRouteImport.update({
  id: '/api/public/attom-health',
  path: '/api/public/attom-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnginesTtsRoute = ApiEnginesTtsRouteImport.update({
  id: '/api/engines/tts',
  path: '/api/engines/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillingReturnRoute =
  AuthenticatedBillingReturnRouteImport.update({
    id: '/return',
    path: '/return',
    getParentRoute: () => AuthenticatedBillingRoute,
  } as any)
const AuthenticatedAppWatchlistRoute =
  AuthenticatedAppWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppVisionRoute = AuthenticatedAppVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVideosRoute = AuthenticatedAppVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTitleSearchRoute =
  AuthenticatedAppTitleSearchRouteImport.update({
    id: '/title-search',
    path: '/title-search',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSocialRoute = AuthenticatedAppSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScoringRoute = AuthenticatedAppScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPropertiesRoute =
  AuthenticatedAppPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOwnersRoute = AuthenticatedAppOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOutreachRoute =
  AuthenticatedAppOutreachRouteImport.update({
    id: '/outreach',
    path: '/outreach',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOptOutsRoute = AuthenticatedAppOptOutsRouteImport.update({
  id: '/opt-outs',
  path: '/opt-outs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLeadListsRoute =
  AuthenticatedAppLeadListsRouteImport.update({
    id: '/lead-lists',
    path: '/lead-lists',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppForeclosureAgentRoute =
  AuthenticatedAppForeclosureAgentRouteImport.update({
    id: '/foreclosure-agent',
    path: '/foreclosure-agent',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContractsRoute =
  AuthenticatedAppContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContactsRoute =
  AuthenticatedAppContactsRouteImport.update({
    id: '/contacts',
    path: '/contacts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuctionsRoute =
  AuthenticatedAppAuctionsRouteImport.update({
    id: '/auctions',
    path: '/auctions',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgentRoute = AuthenticatedAppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPropertiesIndexRoute =
  AuthenticatedAppPropertiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPropertiesRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTwilioVoiceRoute =
  ApiPublicHooksTwilioVoiceRouteImport.update({
    id: '/api/public/hooks/twilio-voice',
    path: '/api/public/hooks/twilio-voice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTwilioSmsRoute = ApiPublicHooksTwilioSmsRouteImport.update({
  id: '/api/public/hooks/twilio-sms',
  path: '/api/public/hooks/twilio-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncDistressedOneRoute =
  ApiPublicHooksSyncDistressedOneRouteImport.update({
    id: '/api/public/hooks/sync-distressed-one',
    path: '/api/public/hooks/sync-distressed-one',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncDistressedRoute =
  ApiPublicHooksSyncDistressedRouteImport.update({
    id: '/api/public/hooks/sync-distressed',
    path: '/api/public/hooks/sync-distressed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSignwellRoute = ApiPublicHooksSignwellRouteImport.update({
  id: '/api/public/hooks/signwell',
  path: '/api/public/hooks/signwell',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOutreachReplyRoute =
  ApiPublicHooksOutreachReplyRouteImport.update({
    id: '/api/public/hooks/outreach-reply',
    path: '/api/public/hooks/outreach-reply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNotifySmsRoute = ApiPublicHooksNotifySmsRouteImport.update({
  id: '/api/public/hooks/notify-sms',
  path: '/api/public/hooks/notify-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksComplianceDigestRoute =
  ApiPublicHooksComplianceDigestRouteImport.update({
    id: '/api/public/hooks/compliance-digest',
    path: '/api/public/hooks/compliance-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCloseAuctionsRoute =
  ApiPublicHooksCloseAuctionsRouteImport.update({
    id: '/api/public/hooks/close-auctions',
    path: '/api/public/hooks/close-auctions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentsSlugPPostSlugRoute = AgentsSlugPPostSlugRouteImport.update({
  id: '/p/$postSlug',
  path: '/p/$postSlug',
  getParentRoute: () => AgentsSlugRoute,
} as any)
const AuthenticatedAppVisionLibraryRoute =
  AuthenticatedAppVisionLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedAppVisionRoute,
  } as any)
const AuthenticatedAppTitleSearchHistoryRoute =
  AuthenticatedAppTitleSearchHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAppTitleSearchRoute,
  } as any)
const AuthenticatedAppSocialComposeRoute =
  AuthenticatedAppSocialComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => AuthenticatedAppSocialRoute,
  } as any)
const AuthenticatedAppSocialBusinessPortfolioRoute =
  AuthenticatedAppSocialBusinessPortfolioRouteImport.update({
    id: '/business-portfolio',
    path: '/business-portfolio',
    getParentRoute: () => AuthenticatedAppSocialRoute,
  } as any)
const AuthenticatedAppSettingsPublicProfileRoute =
  AuthenticatedAppSettingsPublicProfileRouteImport.update({
    id: '/public-profile',
    path: '/public-profile',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppSettingsIntegrationsRoute =
  AuthenticatedAppSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppSettingsRoute,
  } as any)
const AuthenticatedAppPropertiesSearchRoute =
  AuthenticatedAppPropertiesSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedAppPropertiesRoute,
  } as any)
const AuthenticatedAppPropertiesLookupHistoryRoute =
  AuthenticatedAppPropertiesLookupHistoryRouteImport.update({
    id: '/lookup-history',
    path: '/lookup-history',
    getParentRoute: () => AuthenticatedAppPropertiesRoute,
  } as any)
const AuthenticatedAppPropertiesLookupRoute =
  AuthenticatedAppPropertiesLookupRouteImport.update({
    id: '/lookup',
    path: '/lookup',
    getParentRoute: () => AuthenticatedAppPropertiesRoute,
  } as any)
const AuthenticatedAppPropertiesPropertyIdRoute =
  AuthenticatedAppPropertiesPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => AuthenticatedAppPropertiesRoute,
  } as any)
const AuthenticatedAppLeadsLeadIdRoute =
  AuthenticatedAppLeadsLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => AuthenticatedAppLeadsRoute,
  } as any)
const AuthenticatedAppContractsContractIdRoute =
  AuthenticatedAppContractsContractIdRouteImport.update({
    id: '/$contractId',
    path: '/$contractId',
    getParentRoute: () => AuthenticatedAppContractsRoute,
  } as any)
const AuthenticatedAppAuctionsAuctionIdRoute =
  AuthenticatedAppAuctionsAuctionIdRouteImport.update({
    id: '/$auctionId',
    path: '/$auctionId',
    getParentRoute: () => AuthenticatedAppAuctionsRoute,
  } as any)
const AuthenticatedAppAgentThreadIdRoute =
  AuthenticatedAppAgentThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAppAgentRoute,
  } as any)
const AuthenticatedAppAdminContractsRoute =
  AuthenticatedAppAdminContractsRouteImport.update({
    id: '/admin/contracts',
    path: '/admin/contracts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiPublicOauthYoutubeStartRoute =
  ApiPublicOauthYoutubeStartRouteImport.update({
    id: '/api/public/oauth/youtube/start',
    path: '/api/public/oauth/youtube/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthXStartRoute = ApiPublicOauthXStartRouteImport.update({
  id: '/api/public/oauth/x/start',
  path: '/api/public/oauth/x/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthMetaStartRoute = ApiPublicOauthMetaStartRouteImport.update({
  id: '/api/public/oauth/meta/start',
  path: '/api/public/oauth/meta/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthMetaCallbackRoute =
  ApiPublicOauthMetaCallbackRouteImport.update({
    id: '/api/public/oauth/meta/callback',
    path: '/api/public/oauth/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAdminContractsContractIdRoute =
  AuthenticatedAppAdminContractsContractIdRouteImport.update({
    id: '/$contractId',
    path: '/$contractId',
    getParentRoute: () => AuthenticatedAppAdminContractsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/agents/$slug': typeof AgentsSlugRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/agent': typeof AuthenticatedAppAgentRouteWithChildren
  '/app/auctions': typeof AuthenticatedAppAuctionsRouteWithChildren
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/contracts': typeof AuthenticatedAppContractsRouteWithChildren
  '/app/foreclosure-agent': typeof AuthenticatedAppForeclosureAgentRoute
  '/app/lead-lists': typeof AuthenticatedAppLeadListsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/opt-outs': typeof AuthenticatedAppOptOutsRoute
  '/app/outreach': typeof AuthenticatedAppOutreachRoute
  '/app/owners': typeof AuthenticatedAppOwnersRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRouteWithChildren
  '/app/scoring': typeof AuthenticatedAppScoringRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/social': typeof AuthenticatedAppSocialRouteWithChildren
  '/app/title-search': typeof AuthenticatedAppTitleSearchRouteWithChildren
  '/app/videos': typeof AuthenticatedAppVideosRoute
  '/app/vision': typeof AuthenticatedAppVisionRouteWithChildren
  '/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/billing/return': typeof AuthenticatedBillingReturnRoute
  '/api/engines/tts': typeof ApiEnginesTtsRoute
  '/api/public/attom-health': typeof ApiPublicAttomHealthRoute
  '/api/public/lead-notify': typeof ApiPublicLeadNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/contracts': typeof AuthenticatedAppAdminContractsRouteWithChildren
  '/app/agent/$threadId': typeof AuthenticatedAppAgentThreadIdRoute
  '/app/auctions/$auctionId': typeof AuthenticatedAppAuctionsAuctionIdRoute
  '/app/contracts/$contractId': typeof AuthenticatedAppContractsContractIdRoute
  '/app/leads/$leadId': typeof AuthenticatedAppLeadsLeadIdRoute
  '/app/properties/$propertyId': typeof AuthenticatedAppPropertiesPropertyIdRoute
  '/app/properties/lookup': typeof AuthenticatedAppPropertiesLookupRoute
  '/app/properties/lookup-history': typeof AuthenticatedAppPropertiesLookupHistoryRoute
  '/app/properties/search': typeof AuthenticatedAppPropertiesSearchRoute
  '/app/settings/integrations': typeof AuthenticatedAppSettingsIntegrationsRoute
  '/app/settings/public-profile': typeof AuthenticatedAppSettingsPublicProfileRoute
  '/app/social/business-portfolio': typeof AuthenticatedAppSocialBusinessPortfolioRoute
  '/app/social/compose': typeof AuthenticatedAppSocialComposeRoute
  '/app/title-search/history': typeof AuthenticatedAppTitleSearchHistoryRoute
  '/app/vision/library': typeof AuthenticatedAppVisionLibraryRoute
  '/agents/$slug/p/$postSlug': typeof AgentsSlugPPostSlugRoute
  '/api/public/hooks/close-auctions': typeof ApiPublicHooksCloseAuctionsRoute
  '/api/public/hooks/compliance-digest': typeof ApiPublicHooksComplianceDigestRoute
  '/api/public/hooks/notify-sms': typeof ApiPublicHooksNotifySmsRoute
  '/api/public/hooks/outreach-reply': typeof ApiPublicHooksOutreachReplyRoute
  '/api/public/hooks/signwell': typeof ApiPublicHooksSignwellRoute
  '/api/public/hooks/sync-distressed': typeof ApiPublicHooksSyncDistressedRoute
  '/api/public/hooks/sync-distressed-one': typeof ApiPublicHooksSyncDistressedOneRoute
  '/api/public/hooks/twilio-sms': typeof ApiPublicHooksTwilioSmsRoute
  '/api/public/hooks/twilio-voice': typeof ApiPublicHooksTwilioVoiceRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/properties/': typeof AuthenticatedAppPropertiesIndexRoute
  '/app/admin/contracts/$contractId': typeof AuthenticatedAppAdminContractsContractIdRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/meta/start': typeof ApiPublicOauthMetaStartRoute
  '/api/public/oauth/x/start': typeof ApiPublicOauthXStartRoute
  '/api/public/oauth/youtube/start': typeof ApiPublicOauthYoutubeStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/agents/$slug': typeof AgentsSlugRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/app/agent': typeof AuthenticatedAppAgentRouteWithChildren
  '/app/auctions': typeof AuthenticatedAppAuctionsRouteWithChildren
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/app/contacts': typeof AuthenticatedAppContactsRoute
  '/app/contracts': typeof AuthenticatedAppContractsRouteWithChildren
  '/app/foreclosure-agent': typeof AuthenticatedAppForeclosureAgentRoute
  '/app/lead-lists': typeof AuthenticatedAppLeadListsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/opt-outs': typeof AuthenticatedAppOptOutsRoute
  '/app/outreach': typeof AuthenticatedAppOutreachRoute
  '/app/owners': typeof AuthenticatedAppOwnersRoute
  '/app/scoring': typeof AuthenticatedAppScoringRoute
  '/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/app/social': typeof AuthenticatedAppSocialRouteWithChildren
  '/app/title-search': typeof AuthenticatedAppTitleSearchRouteWithChildren
  '/app/videos': typeof AuthenticatedAppVideosRoute
  '/app/vision': typeof AuthenticatedAppVisionRouteWithChildren
  '/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/billing/return': typeof AuthenticatedBillingReturnRoute
  '/api/engines/tts': typeof ApiEnginesTtsRoute
  '/api/public/attom-health': typeof ApiPublicAttomHealthRoute
  '/api/public/lead-notify': typeof ApiPublicLeadNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/contracts': typeof AuthenticatedAppAdminContractsRouteWithChildren
  '/app/agent/$threadId': typeof AuthenticatedAppAgentThreadIdRoute
  '/app/auctions/$auctionId': typeof AuthenticatedAppAuctionsAuctionIdRoute
  '/app/contracts/$contractId': typeof AuthenticatedAppContractsContractIdRoute
  '/app/leads/$leadId': typeof AuthenticatedAppLeadsLeadIdRoute
  '/app/properties/$propertyId': typeof AuthenticatedAppPropertiesPropertyIdRoute
  '/app/properties/lookup': typeof AuthenticatedAppPropertiesLookupRoute
  '/app/properties/lookup-history': typeof AuthenticatedAppPropertiesLookupHistoryRoute
  '/app/properties/search': typeof AuthenticatedAppPropertiesSearchRoute
  '/app/settings/integrations': typeof AuthenticatedAppSettingsIntegrationsRoute
  '/app/settings/public-profile': typeof AuthenticatedAppSettingsPublicProfileRoute
  '/app/social/business-portfolio': typeof AuthenticatedAppSocialBusinessPortfolioRoute
  '/app/social/compose': typeof AuthenticatedAppSocialComposeRoute
  '/app/title-search/history': typeof AuthenticatedAppTitleSearchHistoryRoute
  '/app/vision/library': typeof AuthenticatedAppVisionLibraryRoute
  '/agents/$slug/p/$postSlug': typeof AgentsSlugPPostSlugRoute
  '/api/public/hooks/close-auctions': typeof ApiPublicHooksCloseAuctionsRoute
  '/api/public/hooks/compliance-digest': typeof ApiPublicHooksComplianceDigestRoute
  '/api/public/hooks/notify-sms': typeof ApiPublicHooksNotifySmsRoute
  '/api/public/hooks/outreach-reply': typeof ApiPublicHooksOutreachReplyRoute
  '/api/public/hooks/signwell': typeof ApiPublicHooksSignwellRoute
  '/api/public/hooks/sync-distressed': typeof ApiPublicHooksSyncDistressedRoute
  '/api/public/hooks/sync-distressed-one': typeof ApiPublicHooksSyncDistressedOneRoute
  '/api/public/hooks/twilio-sms': typeof ApiPublicHooksTwilioSmsRoute
  '/api/public/hooks/twilio-voice': typeof ApiPublicHooksTwilioVoiceRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/properties': typeof AuthenticatedAppPropertiesIndexRoute
  '/app/admin/contracts/$contractId': typeof AuthenticatedAppAdminContractsContractIdRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/meta/start': typeof ApiPublicOauthMetaStartRoute
  '/api/public/oauth/x/start': typeof ApiPublicOauthXStartRoute
  '/api/public/oauth/youtube/start': typeof ApiPublicOauthYoutubeStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/features': typeof FeaturesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/agents/$slug': typeof AgentsSlugRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/app/agent': typeof AuthenticatedAppAgentRouteWithChildren
  '/_authenticated/app/auctions': typeof AuthenticatedAppAuctionsRouteWithChildren
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRoute
  '/_authenticated/app/contacts': typeof AuthenticatedAppContactsRoute
  '/_authenticated/app/contracts': typeof AuthenticatedAppContractsRouteWithChildren
  '/_authenticated/app/foreclosure-agent': typeof AuthenticatedAppForeclosureAgentRoute
  '/_authenticated/app/lead-lists': typeof AuthenticatedAppLeadListsRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/opt-outs': typeof AuthenticatedAppOptOutsRoute
  '/_authenticated/app/outreach': typeof AuthenticatedAppOutreachRoute
  '/_authenticated/app/owners': typeof AuthenticatedAppOwnersRoute
  '/_authenticated/app/properties': typeof AuthenticatedAppPropertiesRouteWithChildren
  '/_authenticated/app/scoring': typeof AuthenticatedAppScoringRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRouteWithChildren
  '/_authenticated/app/social': typeof AuthenticatedAppSocialRouteWithChildren
  '/_authenticated/app/title-search': typeof AuthenticatedAppTitleSearchRouteWithChildren
  '/_authenticated/app/videos': typeof AuthenticatedAppVideosRoute
  '/_authenticated/app/vision': typeof AuthenticatedAppVisionRouteWithChildren
  '/_authenticated/app/watchlist': typeof AuthenticatedAppWatchlistRoute
  '/_authenticated/billing/return': typeof AuthenticatedBillingReturnRoute
  '/api/engines/tts': typeof ApiEnginesTtsRoute
  '/api/public/attom-health': typeof ApiPublicAttomHealthRoute
  '/api/public/lead-notify': typeof ApiPublicLeadNotifyRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/contracts': typeof AuthenticatedAppAdminContractsRouteWithChildren
  '/_authenticated/app/agent/$threadId': typeof AuthenticatedAppAgentThreadIdRoute
  '/_authenticated/app/auctions/$auctionId': typeof AuthenticatedAppAuctionsAuctionIdRoute
  '/_authenticated/app/contracts/$contractId': typeof AuthenticatedAppContractsContractIdRoute
  '/_authenticated/app/leads/$leadId': typeof AuthenticatedAppLeadsLeadIdRoute
  '/_authenticated/app/properties/$propertyId': typeof AuthenticatedAppPropertiesPropertyIdRoute
  '/_authenticated/app/properties/lookup': typeof AuthenticatedAppPropertiesLookupRoute
  '/_authenticated/app/properties/lookup-history': typeof AuthenticatedAppPropertiesLookupHistoryRoute
  '/_authenticated/app/properties/search': typeof AuthenticatedAppPropertiesSearchRoute
  '/_authenticated/app/settings/integrations': typeof AuthenticatedAppSettingsIntegrationsRoute
  '/_authenticated/app/settings/public-profile': typeof AuthenticatedAppSettingsPublicProfileRoute
  '/_authenticated/app/social/business-portfolio': typeof AuthenticatedAppSocialBusinessPortfolioRoute
  '/_authenticated/app/social/compose': typeof AuthenticatedAppSocialComposeRoute
  '/_authenticated/app/title-search/history': typeof AuthenticatedAppTitleSearchHistoryRoute
  '/_authenticated/app/vision/library': typeof AuthenticatedAppVisionLibraryRoute
  '/agents/$slug/p/$postSlug': typeof AgentsSlugPPostSlugRoute
  '/api/public/hooks/close-auctions': typeof ApiPublicHooksCloseAuctionsRoute
  '/api/public/hooks/compliance-digest': typeof ApiPublicHooksComplianceDigestRoute
  '/api/public/hooks/notify-sms': typeof ApiPublicHooksNotifySmsRoute
  '/api/public/hooks/outreach-reply': typeof ApiPublicHooksOutreachReplyRoute
  '/api/public/hooks/signwell': typeof ApiPublicHooksSignwellRoute
  '/api/public/hooks/sync-distressed': typeof ApiPublicHooksSyncDistressedRoute
  '/api/public/hooks/sync-distressed-one': typeof ApiPublicHooksSyncDistressedOneRoute
  '/api/public/hooks/twilio-sms': typeof ApiPublicHooksTwilioSmsRoute
  '/api/public/hooks/twilio-voice': typeof ApiPublicHooksTwilioVoiceRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/app/properties/': typeof AuthenticatedAppPropertiesIndexRoute
  '/_authenticated/app/admin/contracts/$contractId': typeof AuthenticatedAppAdminContractsContractIdRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/meta/start': typeof ApiPublicOauthMetaStartRoute
  '/api/public/oauth/x/start': typeof ApiPublicOauthXStartRoute
  '/api/public/oauth/youtube/start': typeof ApiPublicOauthYoutubeStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app'
    | '/billing'
    | '/dashboard'
    | '/agents/$slug'
    | '/api/chat'
    | '/api/transcribe'
    | '/email/unsubscribe'
    | '/app/agent'
    | '/app/auctions'
    | '/app/audit'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/contracts'
    | '/app/foreclosure-agent'
    | '/app/lead-lists'
    | '/app/leads'
    | '/app/notifications'
    | '/app/opt-outs'
    | '/app/outreach'
    | '/app/owners'
    | '/app/properties'
    | '/app/scoring'
    | '/app/settings'
    | '/app/social'
    | '/app/title-search'
    | '/app/videos'
    | '/app/vision'
    | '/app/watchlist'
    | '/billing/return'
    | '/api/engines/tts'
    | '/api/public/attom-health'
    | '/api/public/lead-notify'
    | '/lovable/email/suppression'
    | '/app/'
    | '/app/admin/contracts'
    | '/app/agent/$threadId'
    | '/app/auctions/$auctionId'
    | '/app/contracts/$contractId'
    | '/app/leads/$leadId'
    | '/app/properties/$propertyId'
    | '/app/properties/lookup'
    | '/app/properties/lookup-history'
    | '/app/properties/search'
    | '/app/settings/integrations'
    | '/app/settings/public-profile'
    | '/app/social/business-portfolio'
    | '/app/social/compose'
    | '/app/title-search/history'
    | '/app/vision/library'
    | '/agents/$slug/p/$postSlug'
    | '/api/public/hooks/close-auctions'
    | '/api/public/hooks/compliance-digest'
    | '/api/public/hooks/notify-sms'
    | '/api/public/hooks/outreach-reply'
    | '/api/public/hooks/signwell'
    | '/api/public/hooks/sync-distressed'
    | '/api/public/hooks/sync-distressed-one'
    | '/api/public/hooks/twilio-sms'
    | '/api/public/hooks/twilio-voice'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/properties/'
    | '/app/admin/contracts/$contractId'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/meta/start'
    | '/api/public/oauth/x/start'
    | '/api/public/oauth/youtube/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/billing'
    | '/dashboard'
    | '/agents/$slug'
    | '/api/chat'
    | '/api/transcribe'
    | '/email/unsubscribe'
    | '/app/agent'
    | '/app/auctions'
    | '/app/audit'
    | '/app/campaigns'
    | '/app/contacts'
    | '/app/contracts'
    | '/app/foreclosure-agent'
    | '/app/lead-lists'
    | '/app/leads'
    | '/app/notifications'
    | '/app/opt-outs'
    | '/app/outreach'
    | '/app/owners'
    | '/app/scoring'
    | '/app/settings'
    | '/app/social'
    | '/app/title-search'
    | '/app/videos'
    | '/app/vision'
    | '/app/watchlist'
    | '/billing/return'
    | '/api/engines/tts'
    | '/api/public/attom-health'
    | '/api/public/lead-notify'
    | '/lovable/email/suppression'
    | '/app'
    | '/app/admin/contracts'
    | '/app/agent/$threadId'
    | '/app/auctions/$auctionId'
    | '/app/contracts/$contractId'
    | '/app/leads/$leadId'
    | '/app/properties/$propertyId'
    | '/app/properties/lookup'
    | '/app/properties/lookup-history'
    | '/app/properties/search'
    | '/app/settings/integrations'
    | '/app/settings/public-profile'
    | '/app/social/business-portfolio'
    | '/app/social/compose'
    | '/app/title-search/history'
    | '/app/vision/library'
    | '/agents/$slug/p/$postSlug'
    | '/api/public/hooks/close-auctions'
    | '/api/public/hooks/compliance-digest'
    | '/api/public/hooks/notify-sms'
    | '/api/public/hooks/outreach-reply'
    | '/api/public/hooks/signwell'
    | '/api/public/hooks/sync-distressed'
    | '/api/public/hooks/sync-distressed-one'
    | '/api/public/hooks/twilio-sms'
    | '/api/public/hooks/twilio-voice'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/properties'
    | '/app/admin/contracts/$contractId'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/meta/start'
    | '/api/public/oauth/x/start'
    | '/api/public/oauth/youtube/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/data-deletion'
    | '/features'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/agents/$slug'
    | '/api/chat'
    | '/api/transcribe'
    | '/email/unsubscribe'
    | '/_authenticated/app/agent'
    | '/_authenticated/app/auctions'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/contacts'
    | '/_authenticated/app/contracts'
    | '/_authenticated/app/foreclosure-agent'
    | '/_authenticated/app/lead-lists'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/opt-outs'
    | '/_authenticated/app/outreach'
    | '/_authenticated/app/owners'
    | '/_authenticated/app/properties'
    | '/_authenticated/app/scoring'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/social'
    | '/_authenticated/app/title-search'
    | '/_authenticated/app/videos'
    | '/_authenticated/app/vision'
    | '/_authenticated/app/watchlist'
    | '/_authenticated/billing/return'
    | '/api/engines/tts'
    | '/api/public/attom-health'
    | '/api/public/lead-notify'
    | '/lovable/email/suppression'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/contracts'
    | '/_authenticated/app/agent/$threadId'
    | '/_authenticated/app/auctions/$auctionId'
    | '/_authenticated/app/contracts/$contractId'
    | '/_authenticated/app/leads/$leadId'
    | '/_authenticated/app/properties/$propertyId'
    | '/_authenticated/app/properties/lookup'
    | '/_authenticated/app/properties/lookup-history'
    | '/_authenticated/app/properties/search'
    | '/_authenticated/app/settings/integrations'
    | '/_authenticated/app/settings/public-profile'
    | '/_authenticated/app/social/business-portfolio'
    | '/_authenticated/app/social/compose'
    | '/_authenticated/app/title-search/history'
    | '/_authenticated/app/vision/library'
    | '/agents/$slug/p/$postSlug'
    | '/api/public/hooks/close-auctions'
    | '/api/public/hooks/compliance-digest'
    | '/api/public/hooks/notify-sms'
    | '/api/public/hooks/outreach-reply'
    | '/api/public/hooks/signwell'
    | '/api/public/hooks/sync-distressed'
    | '/api/public/hooks/sync-distressed-one'
    | '/api/public/hooks/twilio-sms'
    | '/api/public/hooks/twilio-voice'
    | '/api/public/webhooks/stripe'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/app/properties/'
    | '/_authenticated/app/admin/contracts/$contractId'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/meta/start'
    | '/api/public/oauth/x/start'
    | '/api/public/oauth/youtube/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  FeaturesRoute: typeof FeaturesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AgentsSlugRoute: typeof AgentsSlugRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiEnginesTtsRoute: typeof ApiEnginesTtsRoute
  ApiPublicAttomHealthRoute: typeof ApiPublicAttomHealthRoute
  ApiPublicLeadNotifyRoute: typeof ApiPublicLeadNotifyRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksCloseAuctionsRoute: typeof ApiPublicHooksCloseAuctionsRoute
  ApiPublicHooksComplianceDigestRoute: typeof ApiPublicHooksComplianceDigestRoute
  ApiPublicHooksNotifySmsRoute: typeof ApiPublicHooksNotifySmsRoute
  ApiPublicHooksOutreachReplyRoute: typeof ApiPublicHooksOutreachReplyRoute
  ApiPublicHooksSignwellRoute: typeof ApiPublicHooksSignwellRoute
  ApiPublicHooksSyncDistressedRoute: typeof ApiPublicHooksSyncDistressedRoute
  ApiPublicHooksSyncDistressedOneRoute: typeof ApiPublicHooksSyncDistressedOneRoute
  ApiPublicHooksTwilioSmsRoute: typeof ApiPublicHooksTwilioSmsRoute
  ApiPublicHooksTwilioVoiceRoute: typeof ApiPublicHooksTwilioVoiceRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicOauthMetaCallbackRoute: typeof ApiPublicOauthMetaCallbackRoute
  ApiPublicOauthMetaStartRoute: typeof ApiPublicOauthMetaStartRoute
  ApiPublicOauthXStartRoute: typeof ApiPublicOauthXStartRoute
  ApiPublicOauthYoutubeStartRoute: typeof ApiPublicOauthYoutubeStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-notify': {
      id: '/api/public/lead-notify'
      path: '/api/public/lead-notify'
      fullPath: '/api/public/lead-notify'
      preLoaderRoute: typeof ApiPublicLeadNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/attom-health': {
      id: '/api/public/attom-health'
      path: '/api/public/attom-health'
      fullPath: '/api/public/attom-health'
      preLoaderRoute: typeof ApiPublicAttomHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engines/tts': {
      id: '/api/engines/tts'
      path: '/api/engines/tts'
      fullPath: '/api/engines/tts'
      preLoaderRoute: typeof ApiEnginesTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/billing/return': {
      id: '/_authenticated/billing/return'
      path: '/return'
      fullPath: '/billing/return'
      preLoaderRoute: typeof AuthenticatedBillingReturnRouteImport
      parentRoute: typeof AuthenticatedBillingRoute
    }
    '/_authenticated/app/watchlist': {
      id: '/_authenticated/app/watchlist'
      path: '/watchlist'
      fullPath: '/app/watchlist'
      preLoaderRoute: typeof AuthenticatedAppWatchlistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vision': {
      id: '/_authenticated/app/vision'
      path: '/vision'
      fullPath: '/app/vision'
      preLoaderRoute: typeof AuthenticatedAppVisionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/videos': {
      id: '/_authenticated/app/videos'
      path: '/videos'
      fullPath: '/app/videos'
      preLoaderRoute: typeof AuthenticatedAppVideosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/title-search': {
      id: '/_authenticated/app/title-search'
      path: '/title-search'
      fullPath: '/app/title-search'
      preLoaderRoute: typeof AuthenticatedAppTitleSearchRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/social': {
      id: '/_authenticated/app/social'
      path: '/social'
      fullPath: '/app/social'
      preLoaderRoute: typeof AuthenticatedAppSocialRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scoring': {
      id: '/_authenticated/app/scoring'
      path: '/scoring'
      fullPath: '/app/scoring'
      preLoaderRoute: typeof AuthenticatedAppScoringRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/properties': {
      id: '/_authenticated/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AuthenticatedAppPropertiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/owners': {
      id: '/_authenticated/app/owners'
      path: '/owners'
      fullPath: '/app/owners'
      preLoaderRoute: typeof AuthenticatedAppOwnersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/outreach': {
      id: '/_authenticated/app/outreach'
      path: '/outreach'
      fullPath: '/app/outreach'
      preLoaderRoute: typeof AuthenticatedAppOutreachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/opt-outs': {
      id: '/_authenticated/app/opt-outs'
      path: '/opt-outs'
      fullPath: '/app/opt-outs'
      preLoaderRoute: typeof AuthenticatedAppOptOutsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/lead-lists': {
      id: '/_authenticated/app/lead-lists'
      path: '/lead-lists'
      fullPath: '/app/lead-lists'
      preLoaderRoute: typeof AuthenticatedAppLeadListsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/foreclosure-agent': {
      id: '/_authenticated/app/foreclosure-agent'
      path: '/foreclosure-agent'
      fullPath: '/app/foreclosure-agent'
      preLoaderRoute: typeof AuthenticatedAppForeclosureAgentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contracts': {
      id: '/_authenticated/app/contracts'
      path: '/contracts'
      fullPath: '/app/contracts'
      preLoaderRoute: typeof AuthenticatedAppContractsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/contacts': {
      id: '/_authenticated/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AuthenticatedAppContactsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/auctions': {
      id: '/_authenticated/app/auctions'
      path: '/auctions'
      fullPath: '/app/auctions'
      preLoaderRoute: typeof AuthenticatedAppAuctionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agent': {
      id: '/_authenticated/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AuthenticatedAppAgentRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/properties/': {
      id: '/_authenticated/app/properties/'
      path: '/'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AuthenticatedAppPropertiesIndexRouteImport
      parentRoute: typeof AuthenticatedAppPropertiesRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/twilio-voice': {
      id: '/api/public/hooks/twilio-voice'
      path: '/api/public/hooks/twilio-voice'
      fullPath: '/api/public/hooks/twilio-voice'
      preLoaderRoute: typeof ApiPublicHooksTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/twilio-sms': {
      id: '/api/public/hooks/twilio-sms'
      path: '/api/public/hooks/twilio-sms'
      fullPath: '/api/public/hooks/twilio-sms'
      preLoaderRoute: typeof ApiPublicHooksTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-distressed-one': {
      id: '/api/public/hooks/sync-distressed-one'
      path: '/api/public/hooks/sync-distressed-one'
      fullPath: '/api/public/hooks/sync-distressed-one'
      preLoaderRoute: typeof ApiPublicHooksSyncDistressedOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-distressed': {
      id: '/api/public/hooks/sync-distressed'
      path: '/api/public/hooks/sync-distressed'
      fullPath: '/api/public/hooks/sync-distressed'
      preLoaderRoute: typeof ApiPublicHooksSyncDistressedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/signwell': {
      id: '/api/public/hooks/signwell'
      path: '/api/public/hooks/signwell'
      fullPath: '/api/public/hooks/signwell'
      preLoaderRoute: typeof ApiPublicHooksSignwellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/outreach-reply': {
      id: '/api/public/hooks/outreach-reply'
      path: '/api/public/hooks/outreach-reply'
      fullPath: '/api/public/hooks/outreach-reply'
      preLoaderRoute: typeof ApiPublicHooksOutreachReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notify-sms': {
      id: '/api/public/hooks/notify-sms'
      path: '/api/public/hooks/notify-sms'
      fullPath: '/api/public/hooks/notify-sms'
      preLoaderRoute: typeof ApiPublicHooksNotifySmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/compliance-digest': {
      id: '/api/public/hooks/compliance-digest'
      path: '/api/public/hooks/compliance-digest'
      fullPath: '/api/public/hooks/compliance-digest'
      preLoaderRoute: typeof ApiPublicHooksComplianceDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/close-auctions': {
      id: '/api/public/hooks/close-auctions'
      path: '/api/public/hooks/close-auctions'
      fullPath: '/api/public/hooks/close-auctions'
      preLoaderRoute: typeof ApiPublicHooksCloseAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug/p/$postSlug': {
      id: '/agents/$slug/p/$postSlug'
      path: '/p/$postSlug'
      fullPath: '/agents/$slug/p/$postSlug'
      preLoaderRoute: typeof AgentsSlugPPostSlugRouteImport
      parentRoute: typeof AgentsSlugRoute
    }
    '/_authenticated/app/vision/library': {
      id: '/_authenticated/app/vision/library'
      path: '/library'
      fullPath: '/app/vision/library'
      preLoaderRoute: typeof AuthenticatedAppVisionLibraryRouteImport
      parentRoute: typeof AuthenticatedAppVisionRoute
    }
    '/_authenticated/app/title-search/history': {
      id: '/_authenticated/app/title-search/history'
      path: '/history'
      fullPath: '/app/title-search/history'
      preLoaderRoute: typeof AuthenticatedAppTitleSearchHistoryRouteImport
      parentRoute: typeof AuthenticatedAppTitleSearchRoute
    }
    '/_authenticated/app/social/compose': {
      id: '/_authenticated/app/social/compose'
      path: '/compose'
      fullPath: '/app/social/compose'
      preLoaderRoute: typeof AuthenticatedAppSocialComposeRouteImport
      parentRoute: typeof AuthenticatedAppSocialRoute
    }
    '/_authenticated/app/social/business-portfolio': {
      id: '/_authenticated/app/social/business-portfolio'
      path: '/business-portfolio'
      fullPath: '/app/social/business-portfolio'
      preLoaderRoute: typeof AuthenticatedAppSocialBusinessPortfolioRouteImport
      parentRoute: typeof AuthenticatedAppSocialRoute
    }
    '/_authenticated/app/settings/public-profile': {
      id: '/_authenticated/app/settings/public-profile'
      path: '/public-profile'
      fullPath: '/app/settings/public-profile'
      preLoaderRoute: typeof AuthenticatedAppSettingsPublicProfileRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/settings/integrations': {
      id: '/_authenticated/app/settings/integrations'
      path: '/integrations'
      fullPath: '/app/settings/integrations'
      preLoaderRoute: typeof AuthenticatedAppSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppSettingsRoute
    }
    '/_authenticated/app/properties/search': {
      id: '/_authenticated/app/properties/search'
      path: '/search'
      fullPath: '/app/properties/search'
      preLoaderRoute: typeof AuthenticatedAppPropertiesSearchRouteImport
      parentRoute: typeof AuthenticatedAppPropertiesRoute
    }
    '/_authenticated/app/properties/lookup-history': {
      id: '/_authenticated/app/properties/lookup-history'
      path: '/lookup-history'
      fullPath: '/app/properties/lookup-history'
      preLoaderRoute: typeof AuthenticatedAppPropertiesLookupHistoryRouteImport
      parentRoute: typeof AuthenticatedAppPropertiesRoute
    }
    '/_authenticated/app/properties/lookup': {
      id: '/_authenticated/app/properties/lookup'
      path: '/lookup'
      fullPath: '/app/properties/lookup'
      preLoaderRoute: typeof AuthenticatedAppPropertiesLookupRouteImport
      parentRoute: typeof AuthenticatedAppPropertiesRoute
    }
    '/_authenticated/app/properties/$propertyId': {
      id: '/_authenticated/app/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/app/properties/$propertyId'
      preLoaderRoute: typeof AuthenticatedAppPropertiesPropertyIdRouteImport
      parentRoute: typeof AuthenticatedAppPropertiesRoute
    }
    '/_authenticated/app/leads/$leadId': {
      id: '/_authenticated/app/leads/$leadId'
      path: '/$leadId'
      fullPath: '/app/leads/$leadId'
      preLoaderRoute: typeof AuthenticatedAppLeadsLeadIdRouteImport
      parentRoute: typeof AuthenticatedAppLeadsRoute
    }
    '/_authenticated/app/contracts/$contractId': {
      id: '/_authenticated/app/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/app/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedAppContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedAppContractsRoute
    }
    '/_authenticated/app/auctions/$auctionId': {
      id: '/_authenticated/app/auctions/$auctionId'
      path: '/$auctionId'
      fullPath: '/app/auctions/$auctionId'
      preLoaderRoute: typeof AuthenticatedAppAuctionsAuctionIdRouteImport
      parentRoute: typeof AuthenticatedAppAuctionsRoute
    }
    '/_authenticated/app/agent/$threadId': {
      id: '/_authenticated/app/agent/$threadId'
      path: '/$threadId'
      fullPath: '/app/agent/$threadId'
      preLoaderRoute: typeof AuthenticatedAppAgentThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppAgentRoute
    }
    '/_authenticated/app/admin/contracts': {
      id: '/_authenticated/app/admin/contracts'
      path: '/admin/contracts'
      fullPath: '/app/admin/contracts'
      preLoaderRoute: typeof AuthenticatedAppAdminContractsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/oauth/youtube/start': {
      id: '/api/public/oauth/youtube/start'
      path: '/api/public/oauth/youtube/start'
      fullPath: '/api/public/oauth/youtube/start'
      preLoaderRoute: typeof ApiPublicOauthYoutubeStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/x/start': {
      id: '/api/public/oauth/x/start'
      path: '/api/public/oauth/x/start'
      fullPath: '/api/public/oauth/x/start'
      preLoaderRoute: typeof ApiPublicOauthXStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta/start': {
      id: '/api/public/oauth/meta/start'
      path: '/api/public/oauth/meta/start'
      fullPath: '/api/public/oauth/meta/start'
      preLoaderRoute: typeof ApiPublicOauthMetaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta/callback': {
      id: '/api/public/oauth/meta/callback'
      path: '/api/public/oauth/meta/callback'
      fullPath: '/api/public/oauth/meta/callback'
      preLoaderRoute: typeof ApiPublicOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/admin/contracts/$contractId': {
      id: '/_authenticated/app/admin/contracts/$contractId'
      path: '/$contractId'
      fullPath: '/app/admin/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedAppAdminContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminContractsRoute
    }
  }
}

interface AuthenticatedAppAgentRouteChildren {
  AuthenticatedAppAgentThreadIdRoute: typeof AuthenticatedAppAgentThreadIdRoute
}

const AuthenticatedAppAgentRouteChildren: AuthenticatedAppAgentRouteChildren = {
  AuthenticatedAppAgentThreadIdRoute: AuthenticatedAppAgentThreadIdRoute,
}

const AuthenticatedAppAgentRouteWithChildren =
  AuthenticatedAppAgentRoute._addFileChildren(
    AuthenticatedAppAgentRouteChildren,
  )

interface AuthenticatedAppAuctionsRouteChildren {
  AuthenticatedAppAuctionsAuctionIdRoute: typeof AuthenticatedAppAuctionsAuctionIdRoute
}

const AuthenticatedAppAuctionsRouteChildren: AuthenticatedAppAuctionsRouteChildren =
  {
    AuthenticatedAppAuctionsAuctionIdRoute:
      AuthenticatedAppAuctionsAuctionIdRoute,
  }

const AuthenticatedAppAuctionsRouteWithChildren =
  AuthenticatedAppAuctionsRoute._addFileChildren(
    AuthenticatedAppAuctionsRouteChildren,
  )

interface AuthenticatedAppContractsRouteChildren {
  AuthenticatedAppContractsContractIdRoute: typeof AuthenticatedAppContractsContractIdRoute
}

const AuthenticatedAppContractsRouteChildren: AuthenticatedAppContractsRouteChildren =
  {
    AuthenticatedAppContractsContractIdRoute:
      AuthenticatedAppContractsContractIdRoute,
  }

const AuthenticatedAppContractsRouteWithChildren =
  AuthenticatedAppContractsRoute._addFileChildren(
    AuthenticatedAppContractsRouteChildren,
  )

interface AuthenticatedAppLeadsRouteChildren {
  AuthenticatedAppLeadsLeadIdRoute: typeof AuthenticatedAppLeadsLeadIdRoute
}

const AuthenticatedAppLeadsRouteChildren: AuthenticatedAppLeadsRouteChildren = {
  AuthenticatedAppLeadsLeadIdRoute: AuthenticatedAppLeadsLeadIdRoute,
}

const AuthenticatedAppLeadsRouteWithChildren =
  AuthenticatedAppLeadsRoute._addFileChildren(
    AuthenticatedAppLeadsRouteChildren,
  )

interface AuthenticatedAppPropertiesRouteChildren {
  AuthenticatedAppPropertiesPropertyIdRoute: typeof AuthenticatedAppPropertiesPropertyIdRoute
  AuthenticatedAppPropertiesLookupRoute: typeof AuthenticatedAppPropertiesLookupRoute
  AuthenticatedAppPropertiesLookupHistoryRoute: typeof AuthenticatedAppPropertiesLookupHistoryRoute
  AuthenticatedAppPropertiesSearchRoute: typeof AuthenticatedAppPropertiesSearchRoute
  AuthenticatedAppPropertiesIndexRoute: typeof AuthenticatedAppPropertiesIndexRoute
}

const AuthenticatedAppPropertiesRouteChildren: AuthenticatedAppPropertiesRouteChildren =
  {
    AuthenticatedAppPropertiesPropertyIdRoute:
      AuthenticatedAppPropertiesPropertyIdRoute,
    AuthenticatedAppPropertiesLookupRoute:
      AuthenticatedAppPropertiesLookupRoute,
    AuthenticatedAppPropertiesLookupHistoryRoute:
      AuthenticatedAppPropertiesLookupHistoryRoute,
    AuthenticatedAppPropertiesSearchRoute:
      AuthenticatedAppPropertiesSearchRoute,
    AuthenticatedAppPropertiesIndexRoute: AuthenticatedAppPropertiesIndexRoute,
  }

const AuthenticatedAppPropertiesRouteWithChildren =
  AuthenticatedAppPropertiesRoute._addFileChildren(
    AuthenticatedAppPropertiesRouteChildren,
  )

interface AuthenticatedAppSettingsRouteChildren {
  AuthenticatedAppSettingsIntegrationsRoute: typeof AuthenticatedAppSettingsIntegrationsRoute
  AuthenticatedAppSettingsPublicProfileRoute: typeof AuthenticatedAppSettingsPublicProfileRoute
}

const AuthenticatedAppSettingsRouteChildren: AuthenticatedAppSettingsRouteChildren =
  {
    AuthenticatedAppSettingsIntegrationsRoute:
      AuthenticatedAppSettingsIntegrationsRoute,
    AuthenticatedAppSettingsPublicProfileRoute:
      AuthenticatedAppSettingsPublicProfileRoute,
  }

const AuthenticatedAppSettingsRouteWithChildren =
  AuthenticatedAppSettingsRoute._addFileChildren(
    AuthenticatedAppSettingsRouteChildren,
  )

interface AuthenticatedAppSocialRouteChildren {
  AuthenticatedAppSocialBusinessPortfolioRoute: typeof AuthenticatedAppSocialBusinessPortfolioRoute
  AuthenticatedAppSocialComposeRoute: typeof AuthenticatedAppSocialComposeRoute
}

const AuthenticatedAppSocialRouteChildren: AuthenticatedAppSocialRouteChildren =
  {
    AuthenticatedAppSocialBusinessPortfolioRoute:
      AuthenticatedAppSocialBusinessPortfolioRoute,
    AuthenticatedAppSocialComposeRoute: AuthenticatedAppSocialComposeRoute,
  }

const AuthenticatedAppSocialRouteWithChildren =
  AuthenticatedAppSocialRoute._addFileChildren(
    AuthenticatedAppSocialRouteChildren,
  )

interface AuthenticatedAppTitleSearchRouteChildren {
  AuthenticatedAppTitleSearchHistoryRoute: typeof AuthenticatedAppTitleSearchHistoryRoute
}

const AuthenticatedAppTitleSearchRouteChildren: AuthenticatedAppTitleSearchRouteChildren =
  {
    AuthenticatedAppTitleSearchHistoryRoute:
      AuthenticatedAppTitleSearchHistoryRoute,
  }

const AuthenticatedAppTitleSearchRouteWithChildren =
  AuthenticatedAppTitleSearchRoute._addFileChildren(
    AuthenticatedAppTitleSearchRouteChildren,
  )

interface AuthenticatedAppVisionRouteChildren {
  AuthenticatedAppVisionLibraryRoute: typeof AuthenticatedAppVisionLibraryRoute
}

const AuthenticatedAppVisionRouteChildren: AuthenticatedAppVisionRouteChildren =
  {
    AuthenticatedAppVisionLibraryRoute: AuthenticatedAppVisionLibraryRoute,
  }

const AuthenticatedAppVisionRouteWithChildren =
  AuthenticatedAppVisionRoute._addFileChildren(
    AuthenticatedAppVisionRouteChildren,
  )

interface AuthenticatedAppAdminContractsRouteChildren {
  AuthenticatedAppAdminContractsContractIdRoute: typeof AuthenticatedAppAdminContractsContractIdRoute
}

const AuthenticatedAppAdminContractsRouteChildren: AuthenticatedAppAdminContractsRouteChildren =
  {
    AuthenticatedAppAdminContractsContractIdRoute:
      AuthenticatedAppAdminContractsContractIdRoute,
  }

const AuthenticatedAppAdminContractsRouteWithChildren =
  AuthenticatedAppAdminContractsRoute._addFileChildren(
    AuthenticatedAppAdminContractsRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgentRoute: typeof AuthenticatedAppAgentRouteWithChildren
  AuthenticatedAppAuctionsRoute: typeof AuthenticatedAppAuctionsRouteWithChildren
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRoute
  AuthenticatedAppContactsRoute: typeof AuthenticatedAppContactsRoute
  AuthenticatedAppContractsRoute: typeof AuthenticatedAppContractsRouteWithChildren
  AuthenticatedAppForeclosureAgentRoute: typeof AuthenticatedAppForeclosureAgentRoute
  AuthenticatedAppLeadListsRoute: typeof AuthenticatedAppLeadListsRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppOptOutsRoute: typeof AuthenticatedAppOptOutsRoute
  AuthenticatedAppOutreachRoute: typeof AuthenticatedAppOutreachRoute
  AuthenticatedAppOwnersRoute: typeof AuthenticatedAppOwnersRoute
  AuthenticatedAppPropertiesRoute: typeof AuthenticatedAppPropertiesRouteWithChildren
  AuthenticatedAppScoringRoute: typeof AuthenticatedAppScoringRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRouteWithChildren
  AuthenticatedAppSocialRoute: typeof AuthenticatedAppSocialRouteWithChildren
  AuthenticatedAppTitleSearchRoute: typeof AuthenticatedAppTitleSearchRouteWithChildren
  AuthenticatedAppVideosRoute: typeof AuthenticatedAppVideosRoute
  AuthenticatedAppVisionRoute: typeof AuthenticatedAppVisionRouteWithChildren
  AuthenticatedAppWatchlistRoute: typeof AuthenticatedAppWatchlistRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminContractsRoute: typeof AuthenticatedAppAdminContractsRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgentRoute: AuthenticatedAppAgentRouteWithChildren,
  AuthenticatedAppAuctionsRoute: AuthenticatedAppAuctionsRouteWithChildren,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRoute,
  AuthenticatedAppContactsRoute: AuthenticatedAppContactsRoute,
  AuthenticatedAppContractsRoute: AuthenticatedAppContractsRouteWithChildren,
  AuthenticatedAppForeclosureAgentRoute: AuthenticatedAppForeclosureAgentRoute,
  AuthenticatedAppLeadListsRoute: AuthenticatedAppLeadListsRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppOptOutsRoute: AuthenticatedAppOptOutsRoute,
  AuthenticatedAppOutreachRoute: AuthenticatedAppOutreachRoute,
  AuthenticatedAppOwnersRoute: AuthenticatedAppOwnersRoute,
  AuthenticatedAppPropertiesRoute: AuthenticatedAppPropertiesRouteWithChildren,
  AuthenticatedAppScoringRoute: AuthenticatedAppScoringRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRouteWithChildren,
  AuthenticatedAppSocialRoute: AuthenticatedAppSocialRouteWithChildren,
  AuthenticatedAppTitleSearchRoute:
    AuthenticatedAppTitleSearchRouteWithChildren,
  AuthenticatedAppVideosRoute: AuthenticatedAppVideosRoute,
  AuthenticatedAppVisionRoute: AuthenticatedAppVisionRouteWithChildren,
  AuthenticatedAppWatchlistRoute: AuthenticatedAppWatchlistRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminContractsRoute:
    AuthenticatedAppAdminContractsRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedBillingRouteChildren {
  AuthenticatedBillingReturnRoute: typeof AuthenticatedBillingReturnRoute
}

const AuthenticatedBillingRouteChildren: AuthenticatedBillingRouteChildren = {
  AuthenticatedBillingReturnRoute: AuthenticatedBillingReturnRoute,
}

const AuthenticatedBillingRouteWithChildren =
  AuthenticatedBillingRoute._addFileChildren(AuthenticatedBillingRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AgentsSlugRouteChildren {
  AgentsSlugPPostSlugRoute: typeof AgentsSlugPPostSlugRoute
}

const AgentsSlugRouteChildren: AgentsSlugRouteChildren = {
  AgentsSlugPPostSlugRoute: AgentsSlugPPostSlugRoute,
}

const AgentsSlugRouteWithChildren = AgentsSlugRoute._addFileChildren(
  AgentsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  FeaturesRoute: FeaturesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AgentsSlugRoute: AgentsSlugRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiEnginesTtsRoute: ApiEnginesTtsRoute,
  ApiPublicAttomHealthRoute: ApiPublicAttomHealthRoute,
  ApiPublicLeadNotifyRoute: ApiPublicLeadNotifyRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksCloseAuctionsRoute: ApiPublicHooksCloseAuctionsRoute,
  ApiPublicHooksComplianceDigestRoute: ApiPublicHooksComplianceDigestRoute,
  ApiPublicHooksNotifySmsRoute: ApiPublicHooksNotifySmsRoute,
  ApiPublicHooksOutreachReplyRoute: ApiPublicHooksOutreachReplyRoute,
  ApiPublicHooksSignwellRoute: ApiPublicHooksSignwellRoute,
  ApiPublicHooksSyncDistressedRoute: ApiPublicHooksSyncDistressedRoute,
  ApiPublicHooksSyncDistressedOneRoute: ApiPublicHooksSyncDistressedOneRoute,
  ApiPublicHooksTwilioSmsRoute: ApiPublicHooksTwilioSmsRoute,
  ApiPublicHooksTwilioVoiceRoute: ApiPublicHooksTwilioVoiceRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicOauthMetaCallbackRoute: ApiPublicOauthMetaCallbackRoute,
  ApiPublicOauthMetaStartRoute: ApiPublicOauthMetaStartRoute,
  ApiPublicOauthXStartRoute: ApiPublicOauthXStartRoute,
  ApiPublicOauthYoutubeStartRoute: ApiPublicOauthYoutubeStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
